var = input('Digite algo: ')
print('O tipo de dado recebido foi', type(var))
print('É numérico? ', var.isnumeric())
print('É alfabético? ', var.isalpha())
print('É alfanumérico? ', var.isalnum())
print('É maiúscula? ', var.isupper())
print('É minúscula? ', var.islower())
print('É decimal? ', var.isdecimal())
