name = str(input('Digite seu nome completo: ')).strip()
nawo = name.split(' ')
print('analizando seu nome... ')
print(name.upper())
print(name.lower())
print('Seu nome tem {} letras'.format(len(name)-name.count(' ')))
# print('O seu primeiro nome tem {} letras'.format(name.find(' ')))
print('Seu primeiro nome é {} e ele tem {} letras'.format(nawo[0], len(nawo[0])))
